services:
  postgres:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
        interval: 5s
        timeout: 5s
        retries: 10

  redis:
      image: redis
      restart: always
      command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    networks:
      - kafka-network
    ports:
      - "9094:9094"
    environment:
## Node identification
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
## Network
      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
## quorum
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
## Replication
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s


  registration-service:
    image: pepegazxc/registration-service:1.0
    container_name: registration-service
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - kafka-network
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_healthy

networks:
  kafka-network:
    driver: bridge
  app-network:
    driver: bridge

volumes:
   pgdata:
   redis_data: